ALTER TABLE `teams`.`requests`
ADD COLUMN `id` BIGINT(20) NOT NULL AUTO_INCREMENT AFTER `timestamp`
, ADD COLUMN `message` TEXT DEFAULT NULL 
, DROP PRIMARY KEY 
, ADD PRIMARY KEY (`id`) 
, ADD UNIQUE INDEX `id_UNIQUE` (`id` ASC) ;

ALTER TABLE `teams`.`invitations` ADD COLUMN `id` BIGINT(20) NOT NULL AUTO_INCREMENT AFTER `inviter`
, DROP PRIMARY KEY
, ADD PRIMARY KEY (`id`)
, ADD UNIQUE INDEX `id_UNIQUE` (`id` ASC) ;
